
[font]
size = 10

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[[keyboard.bindings]]
action = "ScrollLineDown"
key = "J"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ScrollLineUp"
key = "K"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ScrollPageDown"
key = "J"
mods = "Control|Shift|Super"

[[keyboard.bindings]]
action = "ScrollPageUp"
key = "K"
mods = "Control|Shift|Super"

[[keyboard.bindings]]
action = "ToggleViMode"
key = "V"
mods = "Control"

[general]
import = ["/home/urtzi/.config/alacritty/theme.toml"]

[terminal]

[terminal.shell]
program = "/usr/bin/zsh"

[window.padding]
x = 3
y = 3

[keyboard]
