[colors.bright]
black = "#414868"
blue = "#8db0ff"
cyan = "#a4daff"
green = "#9fe044"
magenta = "#c7a9ff"
red = "#ff899d"
white = "#c0caf5"
yellow = "#faba4a"

[colors.cursor]
cursor = "#c0caf5"
text = "#1a1b26"

[colors.normal]
black = "#15161e"
blue = "#7aa2f7"
cyan = "#7dcfff"
green = "#9ece6a"
magenta = "#bb9af7"
red = "#f7768e"
white = "#a9b1d6"
yellow = "#e0af68"

[colors.primary]
background = "#1a1b26"
foreground = "#c0caf5"
