format = """
$username$hostname$directory$git_branch$git_status$git_commit
$character
"""
add_newline = false

[line_break] 
disabled = true

[username]
format = '[$user](purple)'
disabled = false
show_always = true

[hostname]
ssh_only = false
format = '[@$hostname](purple) '
trim_at = '.companyname.com'
disabled = false

[character]
success_symbol = "[](bold green)"
error_symbol = "[](bold red)"
vimcmd_symbol = "[](#d79922)"

[directory]
truncation_length = 8
truncate_to_repo = true
truncation_symbol = '…/'
read_only = " 󰌾"


[git_branch]
format = '[$symbol$branch(:$remote_branch)]($style) '
symbol = " "

[git_status]
format = '([\[$all_status$ahead_behind\]](bold #d79922) )'
ahead = "${count}"
diverged = "${ahead_count}${behind_count}"
behind = "${count}"

[git_commit]
tag_symbol = '  '

[cmd_duration]
disabled = true
