#!/usr/bin/env sh
# modified from https://github.com/gotbletu/fzf-nova

FZF_CONFIG="${FZF_CONFIG:-$HOME/.config/zsh/.fzf_config}"
export FZF_THEME_OPTS="$(grep -m1 '^--color' "$FZF_CONFIG" 2>/dev/null)"

export FZF_DEFAULT_OPTS="$FZF_THEME_OPTS -e -i -d '_' --reverse --with-nth 2.. --info=right --scroll-off=5 --tiebreak=begin --bind 'home:first,end:last,tab:down,shift-tab:up' --bind 'ctrl-t:first,ctrl-b:last'"

mydir="${0%/*}"
selected="$(
  find "$mydir" -type f -name '_*' -exec basename {} \; \
  | sort | sed 's@\.@ @g' | column -t -s ',' \
  | fzf --prompt='fzf-nova: ' | cut -d ' ' -f1
)"
[ -z "$selected" ] && exit
eval "${mydir}/${selected},*"
