vim.pack.add({ "https://github.com/nickjvandyke/opencode.nvim" })

vim.keymap.set({ "n", "x" }, "<leader>io", function()
  require("opencode").select()
end, { desc = "OpenCode actions" })
vim.keymap.set({ "n", "x" }, "<leader>ia", function()
  require("opencode").ask()
end, { desc = "Ask opencode ask" })
vim.keymap.set({ "n", "x" }, "go", function()
  return require("opencode").operator("@this ")
end, { desc = "Add range to opencode", expr = true })
vim.keymap.set("n", "<C-M-b>", function()
  require("opencode").command("session.half.page.up")
end, { desc = "Scroll OpenCode up" })
vim.keymap.set("n", "<C-M-f>", function()
  require("opencode").command("session.half.page.down")
end, { desc = "Scroll OpenCode down" })
